language: python
python:
  - "2.7"
  - "2.6"
install:
 - pip install -r requirements_dev.txt  --use-mirrors
before_script:
 - echo "secret" > django_project/ldap-password
 - PYTHONPATH=. python django_project/first_time_init.py
 - python manage.py syncdb --noinput
 - python manage.py migrate --noinput
script:
 - pyflakes -x W fwadmin
 - coverage run manage.py test fwadmin
after_success:
 - coveralls
