- hosts: servers
  sudo: true

  vars_files:
    - vars.yml 

  tasks:
  # packages
  - name: Install python-apt (manually) as the "apt" ansible module needs it
    shell: apt-get install -y python-apt
  - name: Install apt packages
    apt: pkg=${item} state=installed update-cache=yes
    with_items: ${apt_packages}

  # user setup
  - name: copy user ssh key
    authorized_key: user=ubuntu key='$FILE(~/.ssh/id_rsa.pub)'
  - name: enable SUDO without password
    copy: content='%sudo ALL=(ALL) NOPASSWD:ALL' 
          dest=/etc/sudoers.d/ansible owner=root group=root mode=0440

  # app setup
  - name: create app user
    user: name=${project_user} home=${project_root}
  - name: create application dir
    file: group=${project_user} owner=${project_user} mode=755 state=directory
          path=${item}
    with_items:
      - ${project_root}
      - ${project_root}/application
      - ${project_root}/public_html

  # apache setup
  - name: add apache vhost
    template: owner=root mode=0644 src=templates/apache2-site 
              dest=/etc/apache2/sites-enabled/${project_name}
    notify: reload apache2

  # create DB
  - name: create database "${project_db_name}" db
    mysql_db: db=${project_db_name}
  - name: create db user "${project_db_user}"
    mysql_user: name=${project_db_user} password=${project_db_user_password}
                priv=${project_db_name}.*:ALL
    vars_prompt:
      project_db_user_password: "Please set a password for ${project_db_user}"

  handlers:
    - include: handlers.yml

# do the deploy
- include: deploy.yml

