# customize
project_name: fwadmin
project_git_repo: https://github.com/mvo5/fwadmin.git # use ZIMK later
project_git_version: origin/feature/ansible
project_uses_ldap: True
project_uses_south: True

# should not need customizing
project_root: /srv/${project_name}
project_virtual_env: ${project_root}/venv
project_admin_mail: team_shen@uni-trier.de
project_user: ${project_name}
project_db_user: ${project_name}
project_db_name: ${project_name}_db
project_server_name: ${project_name}
project_server_fqdn: ${project_name}.uni-trier.de

